---
schools:
  Abjuration: Abjuração
  Conjuration: Conjuração
  Divination: Adivinhação
  Enchantment: Encantamento
  Evocation: Evocação
  Illusion: Ilusão
  Necromancy: Necromancia
  Transmutation: Transmutação

classes:
  barbarian: Bárbaro
  bard: Bardo
  cleric: Clérigo
  druid: Druida
  fighter: Guerreiro
  monk: Monge
  paladin: Paladino
  ranger: Patrulheiro
  rogue: Ladino
  sorcerer: Feiticeiro
  warlock: Bruxo
  wizard: Mago

features:
  bardic-inspiration-d6: Inspiração Bárdica (d6)
  bardic-inspiration-d8: Inspiração Bárdica (d8)
  bardic-inspiration-d10: Inspiração Bárdica (d10)
  bardic-inspiration-d12: Inspiração Bárdica (d12)
  jack-of-all-trades: Versatilidade
  song-of-rest-d6: Canção de Descanso (d6)
  song-of-rest-d8: Canção de Descanso (d8)
  song-of-rest-d10: Canção de Descanso (d10)
  song-of-rest-d12: Canção de Descanso (d12)
  countercharm: Contracanto
  font-of-inspiration: Fonte de Inspiração
  expertise: Perícia
  fighting-style-defense: "Estilo de Luta: Defesa"
  fighting-style-archery: "Estilo de Luta: Arquearia"
  fighting-style-dueling: "Estilo de Luta: Duelo"
  fighting-style-two-weapon-fighting: "Estilo de Luta: Duas Armas"
  second-wind: Fôlego
  action-surge-1-use: Surto de Ação
  extra-attack: Ataque Extra

spells:
  cure-wounds: Curar Ferimentos
  healing-word: Palavra Curativa
  detect-magic: Detectar Magia
  identify: Identificar
  charm-person: Enfeitiçar Pessoa
  disguise-self: Disfarçar-se
  faerie-fire: Fogo das Fadas
  sleep: Sono
  thunderwave: Onda Trovejante
  vicious-mockery: Zombaria Viciosa
  invisibility: Invisibilidade
  shatter: Estilhaçar
  calm-emotions: Acalmar Emoções
  detect-thoughts: Detectar Pensamentos
  enhance-ability: Aprimorar Atributo
  suggestion: Sugestão
  hypnotic-pattern: Padrão Hipnótico
  dispel-magic: Dissipar Magia
  fear: Medo
  major-image: Imagem Maior
  tongues: Línguas
  polymorph: Polimorfar
  greater-invisibility: Invisibilidade Maior
  dimension-door: Porta Dimensional
  hold-monster: Imobilizar Monstro
  dominate-person: Dominar Pessoa
  raise-dead: Ressurreição Menor
  awaken: Despertar
  darkness: Escuridão
  thaumaturgy: Taumaturgia
  hellish-rebuke: Repreensão Infernal
