---
subclasses:
  champion: Champion
subclass_descs:
  champion: The archetypal Champion focuses on the development of raw physical power
    honed to deadly perfection. Those who model themselves on this archetype combine
    rigorous training with physical excellence to deal devastating blows.
